from __future__ import annotations

from typing import Protocol

import numpy as np


class AwgPort(Protocol):
    def reset(self) -> None: ...
    def output_on(self, channel: int) -> None: ...
    def set_impedance(self, mode: str, channel: int) -> None: ...
    def set_frequency(self, hz: float, channel: int) -> None: ...
    def get_frequency(self, channel: int) -> float: ...
    def set_amplitude_vpp(self, vpp: float, channel: int) -> None: ...
    def get_amplitude_vpp(self, channel: int) -> float: ...
    def close(self) -> None: ...


class OscPort(Protocol):
    def reset(self) -> None: ...
    def output_on(self, channel: int) -> None: ...
    def set_timebase(self, window_s: float, offset_s: float | None = None) -> None: ...
    def set_vertical(self, channel: int, full_scale_v: float, offset_v: float) -> None: ...
    def get_vertical(self, channel: int) -> tuple[float, float]: ...
    def set_coupling(self, channel: int, mode: str) -> None: ...
    def set_impedance(self, channel: int, mode: str) -> None: ...
    def arm_trigger(self, channel: int, level_v: float) -> None: ...
    def set_free_run(self) -> None: ...
    def single_acquire(self, triggered: bool) -> None: ...
    def read_waveform(self, channel: int, points: int | None) -> tuple[np.ndarray, np.ndarray]: ...
    def get_sample_rate(self) -> float: ...
    def close(self) -> None: ...


class ResourceScannerPort(Protocol):
    def list_resources(self) -> tuple[str, ...]: ...
